openapi: 3.0.0
info:
  version: 1.0.0
  title: Common schemas for Token Management API
paths: { }

components:
  schemas:
    UserId:
      type: string
      description: User ID inside the blockchain system (address)

    Price:
      type: string
      pattern: '^\\d+(\\.\\d{1,18})?$'
      description: Число с точностью до 18 знаков после запятой

    TokenName:
      type: string
      description: Name of the user's tokenized file
    
    Date:
      type: string
      format: date
    
    Filter:
      type: object
      properties:
        token_name:
          $ref: '#/components/schemas/TokenName'
        token_type:
          type: string
        start_date:
          $ref: '#/components/schemas/Date'
        end_date:
          $ref: '#/components/schemas/Date'
        sort_direction:
          $ref: '#/components/schemas/SortDirection'
    
    Cursor:
      type: integer
      description: Limit of tokens_repository to return
    
    Limit:
      type: integer
      description: Cursor to start from
    
    Token:
      type: object
      required:
        - name
        - type
        - price
        - currency_code
        - description
        - is_on_market
      properties:
        name:
          $ref: '#/components/schemas/TokenName'
        type:
          type: string
        description:
          type: string
        price:
          $ref: '#/components/schemas/Price'
        currency_code:
          type: string
        is_on_market:
          type: boolean
    
    SortDirection:
      type: string
      enum:
        - "Asc"
        - "Desc"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
