openapi: 3.0.0
info:
  version: 1.0.0
  title: Token Management API for user screen
  description: API for managing and filtering tokens
servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /market/token:
    get:
      tags:
        - Market
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/UserId'
        - in: query
          name: token_name
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/TokenName'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketGetTokenResponse'
        '404':
          description: File with this token_name not found
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/ErrorResponse'

  /market/token/list:
    get:
      tags:
        - Market
      parameters:
        - in: query
          name: cursor
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/Cursor'
        - in: query
          name: limit
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/Limit'

        # Filters
        - in: query
          name: user_id
          schema:
            $ref: 'common.yaml#/components/schemas/UserId'
        - in: query
          name: name
          schema:
            $ref: 'common.yaml#/components/schemas/TokenName'
        - in: query
          name: type
          schema:
            type: string
        - in: query
          name: start_date
          schema:
            $ref: 'common.yaml#/components/schemas/Date'
        - in: query
          name: end_date
          schema:
            $ref: 'common.yaml#/components/schemas/Date'
        - in: query
          name: sort_direction_on_updated_at
          schema:
            $ref: 'common.yaml#/components/schemas/SortDirection'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketListTokenResponse'

components:
  schemas:
    MarketGetTokenResponse:
      type: object
      required:
        - token
      properties:
        token:
          $ref: 'common.yaml#/components/schemas/Token'
    
    MarketListTokenResponse:
      type: object
      properties:
        tokens:
          type: array
          items:
            $ref: '#/components/schemas/TokenListItems'
        next_cursor:
          type: integer
          
    TokenListItems:
      type: object
      required:
        - user_id
        - name
        - type
        - price
        - currency_code
      properties:
        user_id:
          $ref: 'common.yaml#/components/schemas/UserId'
        name:
          $ref: 'common.yaml#/components/schemas/TokenName'
        type:
          type: string
        price:
          $ref: 'common.yaml#/components/schemas/Price'
        currency_code:
          type: string
    