openapi: 3.0.0
info:
  version: 1.0.0
  title: Token Management API for user screen
  description: API for managing and filtering tokens
servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /user/token/downloadLink:
    get:
      tags:
        - User
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/UserId'
        - in: query
          name: name
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/TokenName'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserTokenDownloadLinkResponse'
        '404':
          description: File with this token name not found
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/ErrorResponse'
  
  /user/token:
    get:
      tags:
        - User
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/UserId'
        - in: query
          name: name
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/TokenName'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserTokenGetResponse'
        '404':
          description: File with this token name not found
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/ErrorResponse'
    
    post:
      tags:
        - User
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserTokenPostRequest'
      responses:
        '200':
          description: OK
        '409':
          description: Token with the same content or name already exists
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/ErrorResponse'

    delete:
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserTokenDeleteRequest'
      responses:
        '200':
          description: OK
        '404':
          description: File with this token name not found
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/ErrorResponse'

    patch:
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserTokenPatchRequest'
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/ErrorResponse'
        '404':
          description: File with this token name not found
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/ErrorResponse'

  /user/token/list:
    get:
      tags:
        - User
      parameters:
        - in: query
          name: cursor
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/Cursor'
        - in: query
          name: limit
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/Limit'
        - in: query
          name: user_id
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/UserId'

        # Filters
        - in: query
          name: name
          schema:
            $ref: 'common.yaml#/components/schemas/TokenName'
        - in: query
          name: type
          schema:
            type: string
        - in: query
          name: start_date
          schema:
            $ref: 'common.yaml#/components/schemas/Date'
        - in: query
          name: end_date
          schema:
            $ref: 'common.yaml#/components/schemas/Date'
        - in: query
          name: sort_direction_on_updated_at
          schema:
            $ref: 'common.yaml#/components/schemas/SortDirection'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserTokenListResponse'

components:
  schemas:
    UserTokenDownloadLinkResponse:
      type: object
      required:
        - link
      properties:
        link:
          type: string
    
    UserTokenListResponse:
      type: object
      properties:
        tokens:
          type: array
          items:
            $ref: 'common.yaml#/components/schemas/ListTokenResponse'
        next_cursor:
          $ref: 'common.yaml#/components/schemas/Cursor'
    
    UserTokenGetResponse:
      type: object
      properties:
        token:
          $ref: 'common.yaml#/components/schemas/Token'
    
    UserTokenPostRequest:
      type: object
      required:
        - user_id
        - file
        - name
        - icon
        - type
        - price
        - currency_code
      properties:
        user_id:
          $ref: 'common.yaml#/components/schemas/UserId'
        file:
          $ref: '#/components/schemas/File'
        name:
          $ref: 'common.yaml#/components/schemas/TokenName'
        type:
          type: string
        price:
          $ref: 'common.yaml#/components/schemas/Price'
        currency_code:
          type: string

    UserTokenDeleteRequest:
      type: object
      required:
        - user_id
        - name
      properties:
        name:
          $ref: 'common.yaml#/components/schemas/TokenName'
        user_id:
          $ref: 'common.yaml#/components/schemas/UserId'

    UserTokenPatchRequest:
      type: object
      required:
        - name
      properties:
        name:
          $ref: 'common.yaml#/components/schemas/TokenName'
        new_name:
          type: string
          example: "example_token_name"
          description: New name of the user's tokenized file
        type:
          type: string
        description:
          type: string
        is_on_market:
          type: boolean
    
    File:
      type: string
      format: binary
      description: File to be tokenized
