#!/bin/bash
# Generate ABIs, BINs and go-wrappers for smart contracts
smart_contracts_names=("Storage")

cd contracts || exit 1

# Generate .abi and .bin files
for smart_contract_name in "${smart_contracts_names[@]}"; do
    solc --abi --bin definitions/${smart_contract_name}.sol -o build --overwrite
done

cd ../backend/contracts || exit 1

# Generate go-wrappers
for smart_contract_name in "${smart_contracts_names[@]}"; do
    lowercase_smart_contract_name=$(echo "$smart_contract_name" | tr '[:upper:]' '[:lower:]')
    abigen --bin=../../contracts/build/${smart_contract_name}.bin x--abi=../../contracts/build/${smart_contract_name}.abi --pkg=contracts --out=${lowercase_smart_contract_name}.go --type ${smart_contract_name}
done

echo "Generation completed"