service:
  host: localhost
  port: 8080

ipfs:
  host: /dns/ipfs/tcp
  port: 5001

hardhat:
  host: http://localhost
  port: 8545
  deployer_private_key: ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
  smart_contract_address:
  
postgres:
  host: localhost
  port: 6543
  user: tokenator-user
  password: pwd
  db: tokenator
